コマンドラインで `--needle` を渡すことで、Needle対応のRIBのボイラープレートコードを生成できるようにする
imairi/RIBsCodeGen pull request #6
Opened 2024-06-04 10:29 UTC by h1d3mun3

2024-07-04 07:26 UTC, imairi commented
👁️

2024-07-04 07:46 UTC, imairi requested changes
README に `--needle` についての使い方の記載をお願いします 🙏

2024-07-05 01:04 UTC, h1d3mun3 commented
@imairi 追記しましたmm

2024-08-13 05:51 UTC, imairi approved these changes
👍 LGTM 👍

2024-08-13 05:51 UTC, merged